//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailableUpdate) DeepCopyInto(out *AvailableUpdate) {
	*out = *in
	in.ReleasedAt.DeepCopyInto(&out.ReleasedAt)
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]PluginVersionPair, len(*in))
		copy(*out, *in)
	}
	in.FoundAt.DeepCopyInto(&out.FoundAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailableUpdate.
func (in *AvailableUpdate) DeepCopy() *AvailableUpdate {
	if in == nil {
		return nil
	}
	out := new(AvailableUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompatibilityOverride) DeepCopyInto(out *CompatibilityOverride) {
	*out = *in
	if in.MinecraftVersions != nil {
		in, out := &in.MinecraftVersions, &out.MinecraftVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompatibilityOverride.
func (in *CompatibilityOverride) DeepCopy() *CompatibilityOverride {
	if in == nil {
		return nil
	}
	out := new(CompatibilityOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GracefulShutdown) DeepCopyInto(out *GracefulShutdown) {
	*out = *in
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GracefulShutdown.
func (in *GracefulShutdown) DeepCopy() *GracefulShutdown {
	if in == nil {
		return nil
	}
	out := new(GracefulShutdown)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindow) DeepCopyInto(out *MaintenanceWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindow.
func (in *MaintenanceWindow) DeepCopy() *MaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchedInstance) DeepCopyInto(out *MatchedInstance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchedInstance.
func (in *MatchedInstance) DeepCopy() *MatchedInstance {
	if in == nil {
		return nil
	}
	out := new(MatchedInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaperMCServer) DeepCopyInto(out *PaperMCServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaperMCServer.
func (in *PaperMCServer) DeepCopy() *PaperMCServer {
	if in == nil {
		return nil
	}
	out := new(PaperMCServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PaperMCServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaperMCServerList) DeepCopyInto(out *PaperMCServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PaperMCServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaperMCServerList.
func (in *PaperMCServerList) DeepCopy() *PaperMCServerList {
	if in == nil {
		return nil
	}
	out := new(PaperMCServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PaperMCServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaperMCServerSpec) DeepCopyInto(out *PaperMCServerSpec) {
	*out = *in
	if in.UpdateDelay != nil {
		in, out := &in.UpdateDelay, &out.UpdateDelay
		*out = new(v1.Duration)
		**out = **in
	}
	out.UpdateSchedule = in.UpdateSchedule
	out.GracefulShutdown = in.GracefulShutdown
	out.RCON = in.RCON
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaperMCServerSpec.
func (in *PaperMCServerSpec) DeepCopy() *PaperMCServerSpec {
	if in == nil {
		return nil
	}
	out := new(PaperMCServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaperMCServerStatus) DeepCopyInto(out *PaperMCServerStatus) {
	*out = *in
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]ServerPluginStatus, len(*in))
		copy(*out, *in)
	}
	if in.AvailableUpdate != nil {
		in, out := &in.AvailableUpdate, &out.AvailableUpdate
		*out = new(AvailableUpdate)
		(*in).DeepCopyInto(*out)
	}
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = new(UpdateHistory)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaperMCServerStatus.
func (in *PaperMCServerStatus) DeepCopy() *PaperMCServerStatus {
	if in == nil {
		return nil
	}
	out := new(PaperMCServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Plugin) DeepCopyInto(out *Plugin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Plugin.
func (in *Plugin) DeepCopy() *Plugin {
	if in == nil {
		return nil
	}
	out := new(Plugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Plugin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginList) DeepCopyInto(out *PluginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Plugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginList.
func (in *PluginList) DeepCopy() *PluginList {
	if in == nil {
		return nil
	}
	out := new(PluginList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PluginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginRef) DeepCopyInto(out *PluginRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginRef.
func (in *PluginRef) DeepCopy() *PluginRef {
	if in == nil {
		return nil
	}
	out := new(PluginRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginSource) DeepCopyInto(out *PluginSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginSource.
func (in *PluginSource) DeepCopy() *PluginSource {
	if in == nil {
		return nil
	}
	out := new(PluginSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginSpec) DeepCopyInto(out *PluginSpec) {
	*out = *in
	out.Source = in.Source
	if in.UpdateDelay != nil {
		in, out := &in.UpdateDelay, &out.UpdateDelay
		*out = new(v1.Duration)
		**out = **in
	}
	in.InstanceSelector.DeepCopyInto(&out.InstanceSelector)
	if in.CompatibilityOverride != nil {
		in, out := &in.CompatibilityOverride, &out.CompatibilityOverride
		*out = new(CompatibilityOverride)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginSpec.
func (in *PluginSpec) DeepCopy() *PluginSpec {
	if in == nil {
		return nil
	}
	out := new(PluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginStatus) DeepCopyInto(out *PluginStatus) {
	*out = *in
	if in.AvailableVersions != nil {
		in, out := &in.AvailableVersions, &out.AvailableVersions
		*out = make([]PluginVersionInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchedInstances != nil {
		in, out := &in.MatchedInstances, &out.MatchedInstances
		*out = make([]MatchedInstance, len(*in))
		copy(*out, *in)
	}
	if in.LastFetched != nil {
		in, out := &in.LastFetched, &out.LastFetched
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginStatus.
func (in *PluginStatus) DeepCopy() *PluginStatus {
	if in == nil {
		return nil
	}
	out := new(PluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginVersionInfo) DeepCopyInto(out *PluginVersionInfo) {
	*out = *in
	if in.MinecraftVersions != nil {
		in, out := &in.MinecraftVersions, &out.MinecraftVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.CachedAt.DeepCopyInto(&out.CachedAt)
	in.ReleasedAt.DeepCopyInto(&out.ReleasedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginVersionInfo.
func (in *PluginVersionInfo) DeepCopy() *PluginVersionInfo {
	if in == nil {
		return nil
	}
	out := new(PluginVersionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginVersionPair) DeepCopyInto(out *PluginVersionPair) {
	*out = *in
	out.PluginRef = in.PluginRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginVersionPair.
func (in *PluginVersionPair) DeepCopy() *PluginVersionPair {
	if in == nil {
		return nil
	}
	out := new(PluginVersionPair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RCONConfig) DeepCopyInto(out *RCONConfig) {
	*out = *in
	out.PasswordSecret = in.PasswordSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RCONConfig.
func (in *RCONConfig) DeepCopy() *RCONConfig {
	if in == nil {
		return nil
	}
	out := new(RCONConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerPluginStatus) DeepCopyInto(out *ServerPluginStatus) {
	*out = *in
	out.PluginRef = in.PluginRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerPluginStatus.
func (in *ServerPluginStatus) DeepCopy() *ServerPluginStatus {
	if in == nil {
		return nil
	}
	out := new(ServerPluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateHistory) DeepCopyInto(out *UpdateHistory) {
	*out = *in
	in.AppliedAt.DeepCopyInto(&out.AppliedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateHistory.
func (in *UpdateHistory) DeepCopy() *UpdateHistory {
	if in == nil {
		return nil
	}
	out := new(UpdateHistory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateSchedule) DeepCopyInto(out *UpdateSchedule) {
	*out = *in
	out.MaintenanceWindow = in.MaintenanceWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSchedule.
func (in *UpdateSchedule) DeepCopy() *UpdateSchedule {
	if in == nil {
		return nil
	}
	out := new(UpdateSchedule)
	in.DeepCopyInto(out)
	return out
}
