apiVersion: mc.k8s.lex.la/v1beta1
kind: Plugin
metadata:
  name: custom-plugin
  namespace: default
spec:
  # Direct URL download — for plugins not published on marketplaces
  # (GitHub releases, private repos, self-hosted, etc.)
  source:
    type: url
    url: "https://github.com/example/my-plugin/releases/download/v1.2.0/my-plugin-1.2.0.jar"

    # Optional SHA256 checksum for integrity verification.
    # If omitted, the operator logs a warning but continues.
    # Generate with: sha256sum my-plugin-1.2.0.jar
    # Replace the placeholder below with the actual checksum of your JAR file.
    checksum: "aabbccdd00112233aabbccdd00112233aabbccdd00112233aabbccdd00112233"

  # Version is auto-extracted from plugin.yml inside the JAR.
  # Specify here as fallback if JAR metadata extraction fails.
  version: "1.2.0"

  # For URL sources, updateStrategy controls how the operator treats the single
  # available version. Since a URL points to a single file (no version history),
  # all strategies behave similarly. Use "latest" for simplicity.
  updateStrategy: latest

  # Apply to all production servers
  instanceSelector:
    matchLabels:
      environment: production
