# Example PaperMCServer with pinned version (auto-update builds)
# Stays on specified version but auto-updates to latest builds
apiVersion: mc.k8s.lex.la/v1alpha1
kind: PaperMCServer
metadata:
  name: pin-server
  namespace: default
  labels:
    environment: production
    type: stable
spec:
  # Pin mode: Pin to version, auto-update to latest build
  updateStrategy: "pin"
  version: "1.21.10"

  # Update schedule
  updateSchedule:
    checkCron: "0 3 * * *"
    maintenanceWindow:
      enabled: true
      cron: "0 4 * * 0"  # Sundays at 4 AM

  # Graceful shutdown
  gracefulShutdown:
    timeout: 300s

  # RCON for remote management
  rcon:
    enabled: true
    port: 25575
    passwordSecret:
      name: pin-server-rcon
      key: password

  # Pod template
  # Note: The operator will use docker.io/lexfrei/papermc:1.21.10-<latest-build>
  podTemplate:
    spec:
      containers:
      - name: minecraft
        image: docker.io/lexfrei/papermc:1.21.10-91
        resources:
          requests:
            memory: "3Gi"
            cpu: "1500m"
          limits:
            memory: "6Gi"
            cpu: "3000m"
        env:
        - name: EULA
          value: "TRUE"
---
apiVersion: v1
kind: Secret
metadata:
  name: pin-server-rcon
  namespace: default
type: Opaque
stringData:
  password: "pin-password-321"
