# Example PaperMCServer with pinned version
# No automatic updates - full control over version and build
apiVersion: mc.k8s.lex.la/v1alpha1
kind: PaperMCServer
metadata:
  name: pinned-server
  namespace: default
  labels:
    environment: staging
    type: stable
spec:
  # Build-pin mode: Specific version and build (no updates)
  updateStrategy: "build-pin"
  version: "1.21.10"
  build: 91

  # Update schedule (only for plugin updates, Paper version is pinned)
  updateSchedule:
    checkCron: "0 3 * * *"
    maintenanceWindow:
      enabled: true
      cron: "0 5 * * 6"  # Saturdays at 5 AM

  # Graceful shutdown
  gracefulShutdown:
    timeout: 300s

  # RCON for remote management
  rcon:
    enabled: true
    port: 25575
    passwordSecret:
      name: pinned-server-rcon
      key: password

  # Pod template
  # Note: The operator will use docker.io/lexfrei/papermc:1.21.10-91
  podTemplate:
    spec:
      containers:
      - name: minecraft
        image: docker.io/lexfrei/papermc:1.21.10-91
        resources:
          requests:
            memory: "3Gi"
            cpu: "1500m"
          limits:
            memory: "6Gi"
            cpu: "3000m"
        env:
        - name: EULA
          value: "TRUE"
---
apiVersion: v1
kind: Secret
metadata:
  name: pinned-server-rcon
  namespace: default
type: Opaque
stringData:
  password: "pinned-password-789"
