# Example PaperMCServer with automatic version management
# The solver will pick the best Paper version compatible with all matched plugins
apiVersion: mc.k8s.lex.la/v1alpha1
kind: PaperMCServer
metadata:
  name: auto-server
  namespace: default
  labels:
    environment: production
    type: modded
spec:
  # Auto mode: Solver picks best version for plugins
  updateStrategy: "auto"

  # Update schedule
  updateSchedule:
    checkCron: "0 3 * * *"
    maintenanceWindow:
      enabled: true
      cron: "0 4 * * 0"  # Sundays at 4 AM

  # Graceful shutdown
  gracefulShutdown:
    timeout: 300s

  # RCON for remote management
  rcon:
    enabled: true
    port: 25575
    passwordSecret:
      name: auto-server-rcon
      key: password

  # Pod template
  # Note: The operator will override the container image based on solver results
  podTemplate:
    spec:
      containers:
      - name: minecraft
        image: docker.io/lexfrei/papermc:latest
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        env:
        - name: EULA
          value: "TRUE"
---
apiVersion: v1
kind: Secret
metadata:
  name: auto-server-rcon
  namespace: default
type: Opaque
stringData:
  password: "auto-password-456"
